import type { Course } from "../types";
import type { PublishedContent } from "./types";

const evidence = (utteranceId: string, start: number, end: number) => ({
  utterance_id: utteranceId,
  start_seconds: start,
  end_seconds: end,
});

export function createPublishedFixture(): PublishedContent {
  return {
    schema_version: "ddock_content_v0.1",
    source: {
      video_id: "fixture-video",
      source_url: "https://www.youtube.com/watch?v=fixture-video",
      title: "Published Fixture",
      channel_name: "Fixture Channel",
      published_at: "2026-08-20T00:00:00Z",
      duration_seconds: 80,
      view_count: 1234,
      like_count: 56,
    },
    video_detail: {
      recommendation: {
        eyebrow: "추천해요",
        title: "직접 설정할 분",
        body: "설정과 실행을 함께 확인합니다.",
        claims: [
          { text: "설정을 확인합니다.", evidence: [evidence("UT-001", 0, 10)] },
        ],
        evidence: [evidence("UT-001", 0, 10)],
      },
      tools: [
        {
          name: "cursor",
          canonical_name: "Cursor",
          url: "https://cursor.com",
          description: "설정에 사용하는 도구",
          evidence: [evidence("UT-001", 0, 10)],
        },
        {
          name: "Example CLI",
          canonical_name: "Example CLI",
          url: null,
          description: "",
          evidence: [evidence("UT-003", 40, 50)],
        },
      ],
      tags: ["Cursor", "MCP"],
      part_preview: [],
    },
    script_chapters: [
      {
        chapter_id: "CH-01",
        order: 1,
        title: "설정",
        start_seconds: 0,
        end_seconds: 40,
        utterance_ids: ["UT-001", "UT-002"],
      },
      {
        chapter_id: "CH-02",
        order: 2,
        title: "실행",
        start_seconds: 40,
        end_seconds: 80,
        utterance_ids: ["UT-004"],
      },
    ],
    catchup_parts: [
      {
        part_id: "PART-01",
        order: 1,
        title: "설정을 준비해요",
        summary: "설정 화면을 엽니다.",
        action_objective: "설정 화면이 열린 상태를 확인한다",
        source_utterance_ids: ["UT-001", "UT-002"],
        action_utterance_ids: ["UT-001", "UT-002"],
        source_script_chapter_ids: ["CH-01"],
        start_seconds: 0,
        end_seconds: 40,
        start_timestamp: "00:00",
        end_timestamp: "00:40",
        evidence: [evidence("UT-001", 0, 10), evidence("UT-002", 20, 30)],
        thumbnail: {
          content_chapter_id: "CCH-01",
          relative_path: "screens/CCH-01.jpg",
          overlap_utterance_count: 2,
          overlap_ratio: 1,
          mapping_method: "source_overlap",
        },
        steps: [
          {
            step_id: "PART-01-STEP-01",
            parent_part_id: "PART-01",
            order: 1,
            action_title: "설정 파일을 열어요",
            action_lines: [
              {
                text: "터미널에서 npm run dev를 실행하고 Settings의 .env 파일을 열어요",
                segments: [
                  { type: "text", text: "터미널에서 " },
                  { type: "command", text: "npm run dev" },
                  { type: "text", text: "를 실행하고 " },
                  { type: "ui_label", text: "Settings" },
                  { type: "text", text: "의 " },
                  { type: "filename", text: ".env" },
                  { type: "text", text: " 파일을 " },
                  { type: "path", text: "/workspace/.env" },
                  { type: "text", text: "에서 열어요" },
                ],
                source_utterance_ids: ["UT-001"],
              },
            ],
            source_utterance_ids: ["UT-001"],
            evidence: [evidence("UT-001", 0, 10)],
            playback_start_seconds: 0,
            playback_end_seconds: 10,
            prompt: {
              text: "컴포넌트를 구현해 줘",
              source_kind: "verbatim",
              evidence: [evidence("UT-001", 0, 10)],
            },
            warning: {
              title: "키를 공유하지 마세요",
              body: "API 키는 공개 저장소에 올리지 마세요.",
              evidence: [evidence("UT-001", 0, 10)],
            },
            learn_more: [
              {
                question: "왜 설정 파일을 쓰나요?",
                body: "키를 코드와 분리할 수 있습니다.",
                source_timestamp: "00:00",
                evidence: [evidence("UT-001", 0, 10)],
              },
            ],
            needs_review: false,
          },
          {
            step_id: "PART-01-STEP-02",
            parent_part_id: "PART-01",
            order: 2,
            action_title: "연결을 확인해요",
            action_lines: [
              {
                text: "연결 상태 확인",
                segments: [],
                source_utterance_ids: ["UT-002"],
              },
            ],
            source_utterance_ids: ["UT-002"],
            evidence: [evidence("UT-002", 20, 30)],
            playback_start_seconds: 20,
            playback_end_seconds: 30,
            prompt: null,
            warning: null,
            learn_more: [],
            needs_review: false,
          },
        ],
        needs_review: false,
        generation_warnings: [],
        excluded_actions: [],
      },
      {
        part_id: "PART-02",
        order: 2,
        title: "결과를 실행해요",
        summary: "실행 결과를 확인합니다.",
        action_objective: "실행 결과가 표시된다",
        source_utterance_ids: ["UT-002", "UT-003", "UT-004"],
        action_utterance_ids: ["UT-003", "UT-004"],
        source_script_chapter_ids: ["CH-01", "CH-02"],
        start_seconds: 20,
        end_seconds: 80,
        start_timestamp: "00:20",
        end_timestamp: "01:20",
        evidence: [evidence("UT-003", 40, 50), evidence("UT-004", 60, 70)],
        thumbnail: {
          content_chapter_id: "CCH-02",
          relative_path: "/img/part2.jpg",
          overlap_utterance_count: 2,
          overlap_ratio: 1,
          mapping_method: "source_overlap",
        },
        steps: [
          {
            step_id: "PART-02-STEP-01",
            parent_part_id: "PART-02",
            order: 1,
            action_title: "명령을 실행해요",
            action_lines: [
              {
                text: "명령 실행",
                segments: [{ type: "text", text: "명령 실행" }],
                source_utterance_ids: ["UT-003"],
              },
            ],
            source_utterance_ids: ["UT-003"],
            evidence: [evidence("UT-003", 40, 50)],
            playback_start_seconds: 40,
            playback_end_seconds: 50,
            prompt: null,
            warning: null,
            learn_more: [],
            needs_review: false,
          },
          {
            step_id: "PART-02-STEP-02",
            parent_part_id: "PART-02",
            order: 2,
            action_title: "결과를 확인해요",
            action_lines: [
              {
                text: "결과 확인",
                segments: [{ type: "text", text: "결과 확인" }],
                source_utterance_ids: ["UT-004"],
              },
            ],
            source_utterance_ids: ["UT-004"],
            evidence: [evidence("UT-004", 60, 70)],
            playback_start_seconds: 60,
            playback_end_seconds: 70,
            prompt: null,
            warning: null,
            learn_more: [],
            needs_review: false,
          },
        ],
        needs_review: false,
        generation_warnings: [],
        excluded_actions: [],
      },
    ],
    script: [
      {
        utterance_id: "UT-001",
        start_seconds: 0,
        end_seconds: 10,
        timestamp: "00:00",
        text: "원본 첫 문장",
        script_chapter_id: "CH-01",
        catchup_part_ids: ["PART-01"],
      },
      {
        utterance_id: "UT-002",
        start_seconds: 20,
        end_seconds: 30,
        timestamp: "00:20",
        text: "두 PART에 속한 원본 문장",
        script_chapter_id: "CH-01",
        catchup_part_ids: ["PART-01", "PART-02"],
      },
      {
        utterance_id: "UT-003",
        start_seconds: 40,
        end_seconds: 50,
        timestamp: "00:40",
        text: "챕터가 없는 원본 문장",
        script_chapter_id: null,
        catchup_part_ids: ["PART-02"],
      },
      {
        utterance_id: "UT-004",
        start_seconds: 60,
        end_seconds: 70,
        timestamp: "01:00",
        text: "실행 결과 원본 문장",
        script_chapter_id: "CH-02",
        catchup_part_ids: ["PART-02"],
      },
    ],
    curation_generation: {
      schema_version: "ddock_content_curation_generation_v0.2",
      status: "published",
      needs_review_count: 0,
      review_reasons: [],
      phase_accounting: [],
    },
  };
}

export function createLegacyCourse(): Course {
  return {
    id: "legacy-route",
    youtubeId: "fixture-video",
    title: "Legacy title",
    breadcrumb: ["동영상", "Legacy"],
    thumbnail: "/img/hero.jpg",
    channel: {
      name: "Legacy channel",
      avatar: "/img/avatar1.jpg",
      url: "https://example.com/channel",
      platform: "유튜브",
    },
    publishedAt: "2020-01-01",
    publishedLabel: "2020년 1월 1일",
    ratingLabel: "5점",
    helpLabel: "도움 5",
    viewLabel: "legacy view",
    viewCountLabel: "999",
    likeLabel: "999",
    tags: ["legacy-tag"],
    recommend: { badge: "legacy", title: "legacy", body: "legacy" },
    tools: [{ name: "Cursor", icon: "/img/tool1.jpg" }],
    toolHighlight: { name: "Legacy", url: "https://legacy.example", desc: "legacy" },
    relatedVideos: [],
    parts: [
      {
        id: "legacy-part",
        partNo: 1,
        chapterNo: "CH 01",
        title: "Legacy part",
        thumbnail: "/img/part1.jpg",
        timeLabel: "00:00-00:10",
        startSec: 0,
        endSec: 10,
        steps: [],
        chapterIds: ["CH-01"],
        summary: "legacy",
        tool: null,
        checkpoint: { text: "legacy" },
      },
    ],
    scriptChapters: [],
    script: [],
    durationLabel: "1분",
  };
}
