import type { ReviewDraft } from "./types";

export function createReviewFixture(): ReviewDraft {
  return {
    schema_version: "ddock_content_review_v0.1",
    source: { video_id: "fixture-video", title: "Admin Review Fixture" },
    video_detail: {
      recommendation: {
        eyebrow: "추천해요",
        title: "설정을 직접 따라할 분",
        body: "설정부터 실행까지 확인할 수 있어요.",
        claims: [
          {
            text: "설정을 직접 따라할 수 있어요.",
            evidence: [
              { utterance_id: "UT-00001", start_seconds: 0, end_seconds: 8 },
            ],
          },
        ],
        evidence: [
          { utterance_id: "UT-00001", start_seconds: 0, end_seconds: 8 },
        ],
      },
      tools: [],
      tags: ["Cursor", "MCP"],
      part_preview: [],
    },
    script_chapters: [
      {
        chapter_id: "CH-01",
        order: 1,
        title: "설정",
        start_seconds: 0,
        end_seconds: 38,
        utterance_ids: ["UT-00001", "UT-00002", "UT-00003", "UT-00004"],
      },
    ],
    script: [
      {
        utterance_id: "UT-00001",
        start_seconds: 0,
        end_seconds: 8,
        timestamp: "00:00",
        text: "Cursor 설정에서 MCP 탭을 열어요.",
        script_chapter_id: "CH-01",
        catchup_part_ids: ["PART-01"],
      },
      {
        utterance_id: "UT-00002",
        start_seconds: 10,
        end_seconds: 18,
        timestamp: "00:10",
        text: "실제 프롬프트는 컴포넌트를 구현해 줘 입니다.",
        script_chapter_id: "CH-01",
        catchup_part_ids: ["PART-01"],
      },
      {
        utterance_id: "UT-00003",
        start_seconds: 20,
        end_seconds: 28,
        timestamp: "00:20",
        text: "API 키는 .env 파일에 저장하세요.",
        script_chapter_id: "CH-01",
        catchup_part_ids: [],
      },
      {
        utterance_id: "UT-00004",
        start_seconds: 30,
        end_seconds: 38,
        timestamp: "00:30",
        text: "실행 버튼을 눌러 결과를 확인해요.",
        script_chapter_id: "CH-01",
        catchup_part_ids: [],
      },
    ],
    draft_parts: [
      {
        part_id: "PART-01",
        order: 1,
        title: "MCP 설정을 준비해요",
        summary: "설정 화면을 엽니다.",
        action_objective: "MCP 설정 화면을 연다",
        source_utterance_ids: ["UT-00001", "UT-00002"],
        action_utterance_ids: ["UT-00001", "UT-00002"],
        source_script_chapter_ids: ["CH-01"],
        start_seconds: 0,
        end_seconds: 18,
        start_timestamp: "00:00",
        end_timestamp: "00:18",
        evidence: [
          { utterance_id: "UT-00001", start_seconds: 0, end_seconds: 8 },
          { utterance_id: "UT-00002", start_seconds: 10, end_seconds: 18 },
        ],
        thumbnail: null,
        steps: [
          {
            step_id: "PART-01-STEP-01",
            parent_part_id: "PART-01",
            order: 1,
            action_title: "MCP 탭을 열어요",
            action_lines: [
              {
                text: "Cursor 설정에서 MCP 탭 열기",
                segments: [{ type: "text", text: "Cursor 설정에서 MCP 탭 열기" }],
                source_utterance_ids: ["UT-00001"],
              },
            ],
            source_utterance_ids: ["UT-00001"],
            evidence: [
              { utterance_id: "UT-00001", start_seconds: 0, end_seconds: 8 },
            ],
            playback_start_seconds: 0,
            playback_end_seconds: 8,
            prompt: null,
            warning: null,
            learn_more: [],
            needs_review: false,
          },
        ],
        needs_review: false,
        review_reasons: [],
        generation_warnings: [],
        excluded_actions: [],
      },
    ],
    action_phases: [
      {
        phase_id: "PHASE-001",
        order: 1,
        phase_label: "MCP 설정",
        operation: "MCP 탭을 연다",
        tool_or_surface: "Cursor",
        expected_result: "MCP 설정 화면이 열린다",
        action_utterance_ids: ["UT-00001"],
        context_utterance_ids: ["UT-00002"],
        assigned_part_id: "PART-01",
        needs_review: false,
        review_reasons: [],
      },
      {
        phase_id: "PHASE-002",
        order: 2,
        phase_label: "실행 확인",
        operation: "실행 버튼을 눌러 결과를 확인한다",
        tool_or_surface: "실행 화면",
        expected_result: "실행 결과를 확인한다",
        action_utterance_ids: ["UT-00004"],
        context_utterance_ids: ["UT-00003"],
        assigned_part_id: null,
        needs_review: true,
        review_reasons: ["unassigned_phase"],
      },
    ],
    unassigned_phases: [
      {
        phase_id: "PHASE-002",
        order: 2,
        phase_label: "실행 확인",
        operation: "실행 버튼을 눌러 결과를 확인한다",
        tool_or_surface: "실행 화면",
        expected_result: "실행 결과를 확인한다",
        action_utterance_ids: ["UT-00004"],
        context_utterance_ids: ["UT-00003"],
        assigned_part_id: null,
        needs_review: true,
        review_reasons: ["unassigned_phase"],
        excluded_reason: null,
      },
    ],
    review_queue: [
      {
        review_id: "REV-001",
        type: "unassigned_phase",
        severity: "blocking",
        part_id: null,
        phase_id: "PHASE-002",
        step_id: null,
        utterance_ids: ["UT-00004"],
        message: "Assign, create a PART, or explicitly exclude this phase.",
      },
      {
        review_id: "REV-002",
        type: "script_not_human_verified",
        severity: "warning",
        part_id: null,
        phase_id: null,
        step_id: null,
        utterance_ids: [],
        message: "Script has not been fully human verified.",
      },
    ],
    curation_generation: {
      schema_version: "ddock_content_curation_generation_v0.2",
      status: "completed_with_review",
      needs_review_count: 1,
      review_reasons: ["unassigned_phase"],
      phase_accounting: [],
    },
  };
}
